### ISSUE TITLE
被覆盖在底部的覆盖物被点击的问题

### ISSUE THREAD

**Issue by yilongchun** [Mr-yuwei/YWLJMapView#1]
当覆盖物有多个在同一个点 点击被覆盖在底部的markerview 他的文字无法显示在最外面 还是被上面的挡着，这个问题要怎么处理

**Comment by Mr-yuwei** [comment]
点击覆盖物的时候你可以拿到对应的地理位置，然后删除点击的覆盖物，添加新的覆盖物，最后设置地图的center，但是这样做比较粗暴，我有时间研究一下，感谢提的意见.

**Comment by yilongchun** [comment]
百度地图有个isSelectedAnnotationViewFront属性，设置为YES就可以了。

**Comment by Mr-yuwei** [comment]
好的
